function VCSEL_T_Import = VCSEL_T_Import(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VCSEL_T_IMPORT = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  VCSEL_T_IMPORT = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  VCSEL_T_Import = importfile("C:\Users\metal\Desktop\ExperimetosVCSEL_T_Amplitud\Interrogacion VCSEL T\Interrogacion Temperatura\VCSEL_T_SSFBG_Amplitud_S1R_16000.0samples_Temp_562_Frequency_16_Iterations_41_Temp_Mount_20.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Nov-2023 20:54:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["MuestrasDeLaDAQ", "Tension_SSFBG", "Tension_Referencia", "Tension_Trigger", "Temperatura_Laser", "TiempoTotal"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
VCSEL_T_Import = readtable(filename, opts);

end