function VCSEL_T = VCSEL_T(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VCSEL_T = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  VCSEL_T = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  VCSEL_T = importfile("C:\Users\metal\Desktop\Caracterizacion VCSEL T\VCSEL_1550_T_Caracterizacion_15_11_2023_Temp_562_Voltaje_Step_1_OPM_OSA_1_muestra.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Nov-2023 05:28:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Voltaje_Ideal", "Wavelength", "Power"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
VCSEL_T = readtable(filename, opts);

end