function Fotodiodo_No_Amp = Fotodiodo_No_Amp(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FOTODIODO_NO_AMP = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  FOTODIODO_NO_AMP = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Fotodiodo_No_Amp = importfile("C:\Users\metal\Desktop\ExperimetosVCSEL_T_Amplitud\Caracterizacion Fotodiodo VCSEL T\No_Amp\REF\Fotodiodo_FGA01FC_17_11_2023_12h_47m_Temp_VCSEL_T_562_Voltaje_Step_1_Multimeter_OPM1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Nov-2023 14:56:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Voltaje_VCSEL", "Power", "Voltaje_Photodiode"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Fotodiodo_No_Amp = readtable(filename, opts);

end